---
- name: Download AWS Log installer
  get_url:
    url: "{{ aws_log_agent_url }}"
    dest: /tmp/awslogs-agent-setup.py

- include_vars: cloudwatch_logs.yml

- name: Make sure the AWS Logs config is present
  template:
    src: awslogs.conf.j2
    dest: /tmp/awslogs.conf

- name: Install AWS Logs deamon
  command: /usr/bin/python /tmp/awslogs-agent-setup.py -n -r {{ aws_region }} -c /tmp/awslogs.conf
